title: Animation Throwdown Knowledge Base
short_title: Cartoon Battle
baseurl: ""
url: "https://cartoon-battle.github.io"
images_cdn: "https://cartoon-battle.narzekasz.pl/"
cards_url: "https://cb-live.synapse-games.com/assets/"

google_analytics_key: 'UA-89005212-1'

markdown: kramdown
permalink: :title

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

